version: '3.7'

services:
  web:
    command: bash -c "yarn install && yarn start"
    build: .
    stdin_open: true
    tty: true
    volumes:
      - '.:/app'
      - node_modules:/node_modules
    ports:
      - 3000:3000
volumes:
  node_modules:
